services:

  ###############################################################################
  # Python Linky application
  linky2db:
    command: python src/linky2db.py
    restart: always
    devices:
      - ${LINKY_USB_DEVICE}:${LINKY_USB_DEVICE}

  ###############################################################################
  # MySQL Database
  mysql:
    restart: always

  ###############################################################################
  # Grafana
  grafana:
    restart: always

  ###############################################################################
  # NginX
  nginx:
    container_name: nginx
    profiles: ["https"]
    image: nginxproxy/nginx-proxy
    restart: always
    env_file: .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  ###############################################################################
  # LetsEncrypt
  letsencrypt:
    container_name: letsencrypt
    profiles: ["https"]
    image: nginxproxy/acme-companion
    restart: always
    env_file: .env
    volumes_from:
      - nginx
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

###############################################################################
# MySQL volume
volumes:
  conf:
  vhost:
  html:
  certs:
  acme: