services:

  ###############################################################################
  # Python Linky application
  linky2db:
    command: sleep infinity
    devices: []
    volumes:
      - .:/app
