services:

  ###############################################################################
  # Python Linky application
  linky2db:
    environment:
      PRODUCTION_DB_HOST: ${PRODUCTION_DB_HOST}
      PRODUCTION_DB_PORT: ${PRODUCTION_DB_PORT}
      PRODUCTION_DB_NAME: ${PRODUCTION_DB_NAME}
      PRODUCTION_DB_USER: ${PRODUCTION_DB_USER}
      PRODUCTION_DB_PASSWORD: ${PRODUCTION_DB_PASSWORD}
    volumes:
      - ./src:/linky2db

  ###############################################################################
  # Grafana
  grafana:
    ports:
      - 3000:3000
