apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    isDefault: true
    url: mysql:3306
    user: ${GRAFANA_MYSQL_USER}
    jsonData:
      database: ${MYSQL_DATABASE}
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: ${GRAFANA_MYSQL_PASSWORD}
