name: Backup MySQL database
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
jobs:
  backup-database:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Backup MySQL database
        run: ./scripts/mysql_backup.sh
      - name: Upload latest MySQL backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "./linkystat_mysql_backup.sql.gz"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true
      - name: Upload timestamped MySQL backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "./linkystat_mysql_backup.sql.gz"
          name: "linkystat_mysql_backup.${{ steps.date.outputs.timestamp }}.sql.gz"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true