name: Backup MySQL database
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  backup-database:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: 'Backup MySQL database'
        run: scripts/mysql_backup.sh