name: "MySQL: Backup database"

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  backup-database:
    name: Backup to Google Drive
    runs-on: [self-hosted, Linux, ARM64, raspberrypi_rsaikali]
    steps:
      - uses: actions/checkout@v4

      - name: Load environment from Pi
        run: cat ~/linkystat/.env >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d.%H%M%S')" >> $GITHUB_OUTPUT

      - name: Backup MySQL database
        run: |
          cd ~/linkystat
          ./scripts/mysql_backup.sh

      - name: Upload latest backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "~/linkystat/linkystat_mysql_backup.sql.gz"
          name: "${{ env.VIRTUAL_HOST }}.sql.gz"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true

      - name: Upload timestamped backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "~/linkystat/linkystat_mysql_backup.sql.gz"
          name: "${{ env.VIRTUAL_HOST }}.${{ steps.date.outputs.timestamp }}.sql.gz"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true
