name: "MySQL: Backup database"
on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        default: 'raspberrypi_rsaikali'
        required: true
jobs:
  backup-database:
    runs-on:
      - self-hosted
      - ${{ inputs.environment == '' && 'raspberrypi_rsaikali' || inputs.environment }}
    environment: 
        name: ${{ inputs.environment == '' && 'raspberrypi_rsaikali' || inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "timestamp=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: 'Get MySQL backup filenames'
        id: backup_filenames
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          echo "latest=$(cat .env | grep VIRTUAL_HOST | cut -d '=' -f 2).sql.gz" >> $GITHUB_OUTPUT  
          echo "timestamped=$(cat .env | grep VIRTUAL_HOST | cut -d '=' -f 2).${{ steps.date.outputs.timestamp }}.sql.gz" >> $GITHUB_OUTPUT
      - name: Backup MySQL database
        run: ./scripts/mysql_backup.sh
      - name: Upload latest MySQL backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "./linkystat_mysql_backup.sql.gz"
          name: "${{ steps.backup_filenames.outputs.latest }}"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true
      - name: Upload timestamped MySQL backup to Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "./linkystat_mysql_backup.sql.gz"
          name: "${{ steps.backup_filenames.outputs.timestamped }}"
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          parent_folder_id: 1vXUlIfsEXpzthi_mttXSkuZajfyWG6a5
          override: true