name: "MySQL: Restore database"
on:
  workflow_dispatch:
jobs:
  restore-database:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: akiojin/decode-base64-github-action@v0.1.0
        id: decode-base64
        with:
          base64: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
      - name: 'Get MySQL backup filenames'
        id: backup_filenames
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env
          source .env
          echo "latest=$VIRTUAL_HOST.sql.gz" >> $GITHUB_OUTPUT  
      - name: Download backup file from Google Drive
        uses: k0staa/download-gdrive-file-action@v1
        with:
          service-account-key-json: ${{ steps.decode-base64.outputs.decoded }}
          download-file-name: ${{ steps.backup_filenames.outputs.latest }}
      - name: Restore MySQL database
        run: ./scripts/mysql_restore.sh ${PWD}/${{ steps.backup_filenames.outputs.latest }}